# Generated by Django 3.0.6 on 2020-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_auto_20200508_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebitcredit',
            name='extra_custom_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
