# Generated by Django 3.0.6 on 2020-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_remove_account_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdebitcredit',
            name='customer',
        ),
    ]
