# Generated by Django 3.0.6 on 2020-05-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_app', '0003_auto_20200508_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_debit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerDebitCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_credit', models.FloatField()),
                ('customer_debit', models.FloatField(default=0)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer_credit_debit',
            field=models.ManyToManyField(to='accounts_app.CustomerDebitCredit'),
        ),
    ]
