# Generated by Django 3.0.6 on 2020-05-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_auto_20200508_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer_credit_debit',
        ),
        migrations.AddField(
            model_name='customerdebitcredit',
            name='customer_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.Account'),
            preserve_default=False,
        ),
    ]
