# Generated by Django 3.0.6 on 2020-05-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_customerdebitcredit_extra_custom_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ordered_items',
        ),
    ]
