# Generated by Django 3.0.6 on 2020-05-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0017_auto_20200518_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdebitcredit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ordered',
            options={'ordering': ['-created_at']},
        ),
    ]
